spring:
  application:
    name: product-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product_database_test1?createDatabaseIfNotExist=true
    password: 1234
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password: default_pass_of_your_choice
      connect-timeout: 2000ms
      lettuce:
        pool:
          max-idle: 8
          max-active: 8
          min-idle: 0
