server:
  port: 9999

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      server:
        webflux:
          routes:
            -  id: service-route
               uri: lb:/service-name
               predicates:
                 - Path=/api/order
                 - Path=/api/order/**
