
spring:
  application:
    name: config-server

  profiles:
    active: native
#    active: default
  cloud:
    config:
      server:
#       config github file
#        git:
#          uri: https://github.com/nttho
#          default-label: main
#          clone-on-start: true
        # config-file
        native:
          search-locations: file:///D:/microservice-rikkei/session06-restemplate-feignclient/practice/config-file


server:
  port: 8888