spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: category-route
          uri: lb://category-service
          predicates:
            - Path=/api/greeting/**
