server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: category-route
          uri: lb://category-service
          predicates:
            - Path=/api/greeting/**, /api/categories/**
        - id: product-route
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
        - id: order-route
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: DEBUG