spring:
  application:
    name: eureka-server
  cloud:
    config:
      allow-override:
      server:
        git:
          uri: https://github.com/Ntttho/learn-microservice-mine/tree/main/session03/config/config-repo
          default-label: main
          clone-on-start: true
#  cloud:
#    config:
#      server:
#        native:
#          search-locations:

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false